version: "3.8"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  redis_db:
#    container_name: cube-redis
#    image: redis
#    ports:
#      - "6379"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
  backend:
    tty: true
    restart: on-failure
    build: ./backend/
    volumes:
      - ./backend/src:/home/python/app/src
      - ./backend/assets:/home/python/app/assets
      - backend_env:/home/python/.local
      - backend_extensions:/home/python/.vscode-server
      - ./.env:/home/python/app/src/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    container_name: wepledge-frontend
    tty: true
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/:/home/node/app
      - frontend_nodemodules:/home/node/app/node_modules
      - frontend_extensions:/home/node/.vscode-server
    ports:
      - "3000:3000"

volumes:
  frontend_nodemodules:
  frontend_extensions:
  backend_env:
  backend_extensions:
  db-data:
  pgadmin-data:
  cube_nodemodules:
  cube_extensions:
