version: "3.8"
services:
  frontend:
    container_name: wepledge-frontend
    tty: true
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/:/home/node/app
      - frontend_nodemodules:/home/node/app/node_modules
      - frontend_extensions:/home/node/.vscode-server
    # depends_on:
    #   - cube
    ports:
      - "3000:3000"
    env_file: ./.env
    environment:
      HOME: /home/node
volumes:
  frontend_nodemodules:
  frontend_extensions:
